---
- name: Hello Rahi
  hosts: all
  become: yes
  remote_user: root
  tasks:
   - name: Update required packages
     shell: yum update -y
   - name: Install NPM
     yum:
       name: npm
       state: latest
   - name: Install Nginx
     yum:
       name: nginx
       state: latest
   - name: Install 
     yum:
       name: nodejs
       state: latest
   - name: Create a symbolic link
     file:
        path: /var/www/jenkins-react-app
  