---
- name: Hello Rahi
  hosts: all
  become: yes
  remote_user: root
  tasks:
  #  - name: Update required packages
  #    shell: yum update -y
     - name: Install git
       yum:
         name: git
         state: latest
    #  - name: shell nginx
    #    shell: amazon-linux-extras enable nginx
     - name: Install nginx
       yum:
         name: nginx
         state: latest
  #  - name: Upgrade all packages, excluding kernel & foo related packages
  #    yum:
  #     name: '*'
  #     state: latest
    #  - name: Install epel
    #    yum:
    #      name: epel-release
    #      state: present
     - name: Install 
       yum:
         name: firefox
         state: latest
  #  - name: Create a symbolic link
  #    file:
  #       path: /var/www/jenkins-react-app
  